data_file: data/game_log.csv
bet_vector:
  cars:
    "0": "紅車"
    "1": "藍車"
    "2": "綠車"
    "3": "黃車"
    "4": "紫車"
    "5": "橘車"
    "6": "黑車"
    "7": "白車"
  odd:
    "0": 5 
    "1": 5
    "2": 5
    "3": 5
    "4": 10
    "5": 15
    "6": 25
    "7": 45

columns:
  - timestamp
  - round
  - bet
  - winner

