data_file: data/game_log.csv
bet_vector:
  cars:
    "0": "聯結機"
    "1": "大卡車"
    "2": "特斯拉"
    "3": "野馬"
    "4": "保時捷"
    "5": "賓士大G"
    "6": "麥克拉倫"
    "7": "藍博基尼"
  odd:
    "0": 5 
    "1": 5
    "2": 5
    "3": 5
    "4": 10
    "5": 15
    "6": 25
    "7": 45

columns:
  - timestamp
  - round
  - bet
  - winner

car_type:
  small_cars: [0, 1, 2, 3]  # 根據車輛編號來定義小車的車輛
  large_cars: [4, 5, 6, 7]  # 大車的車輛編號

q_learning_params:
  epsilon: 0.9  # 探索的機率
  alpha: 0.1    # 學習率
  gamma: 0.9    # 折扣因子
  actions: [0, 1]  # 動作：0 代表不下注, 1 代表下注
