data_file: data/game_log.csv
bet_vector:
  cars:
    "0": "聯結機"
    "1": "大卡車"
    "2": "特斯拉"
    "3": "野馬"
    "4": "保時捷"
    "5": "賓士大G"
    "6": "麥克拉倫"
    "7": "藍博基尼"
  odd:
    "0": 5 
    "1": 5
    "2": 5
    "3": 5
    "4": 10
    "5": 15
    "6": 25
    "7": 45

columns:
  - timestamp
  - round
  - bet
  - winner

